user_register:
    resource: "@UserBundle/Resources/config/routing/registration.xml"
    prefix: /

user_login:
    resource: "@UserBundle/Resources/config/routing/login.xml"
    prefix: /

home:
    resource: "@HomeBundle/Resources/config/routing/home.xml"
    prefix: /


