user_register:
    resource: "@UserBundle/Resources/config/routing/registration.xml"
    prefix: /

user_login:
    resource: "@UserBundle/Resources/config/routing/login.xml"
    prefix: /

home:
    resource: "@HomeBundle/Resources/config/routing/home.xml"
    prefix: /

profile:
    resource: "@UserBundle/Resources/config/routing/profile.xml"
    prefix: /
feeder:
    resource: "@FeederBundle/Resources/config/routing/feed.xml"
    prefix: /

filter:
    resource: "@FeederBundle/Resources/config/routing/filter.xml"
    prefix: /

config:
    resource: "@ConfigBundle/Resources/config/routing/config.xml"
    prefix: /



