security:
    encoders:
        Dogfeeder\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
         user:
            entity:
                class: UserBundle:User
                property: username

    firewalls:
         frontend_area:
            pattern: ^/
            anonymous: ~
            provider: user
            form_login:
                login_path: user_security_login
                check_path: user_security_logincheck
            logout:
                path: user_security_logout
                target: user_registration_register

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/home, roles: ROLE_ADMIN }