security:
    providers:
        in_memory:
            memory: ~
    encoders:
        Dogfeeder\UserBundle\Entity\User: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~