services:
    user.form.registration:
        class: DogFeeder\UserBundle\Form\Type\UserRegistrationType
        tags:
            - { name: form.type, alias: user_registration }
        arguments: ['@translator.default']

    user.edit:
        class: DogFeeder\UserBundle\Form\Type\UserType
        tags:
            - { name: form.type, alias: user_edit }
        arguments: ['@translator.default']

    config.type:
        class: DogFeeder\ConfigBundle\Form\Type\ConfigType
        tags:
            - { name: form.type, alias: config_add }
        arguments: ['@translator.default']

    feeder.type:
            class: DogFeeder\FeederBundle\Form\Type\FeederType
            tags:
                - { name: form.type, alias: feeder_edit }

    filter.type:
        class: DogFeeder\FeederBundle\Form\Type\FilterType
        tags:
            - { name: form.type, alias: feedstat_filter }
        arguments: ['@security.token_storage', '@translator.default']

    manualfeed.type:
        class: DogFeeder\FeederBundle\Form\Type\ManualFeedType
        tags:
            - { name: form.type, alias: manualfeed_type }
        arguments: ['@security.token_storage']

    app.contains_alphanumeric_validator:
        class: DogFeeder\UserBundle\Form\Validator\Constraints\OnlyAlphaNumericValidator
        tags:
            - { name: validator.constraint_validator }
        arguments: ['@translator.default']

    app.only_numeric_validator:
        class: DogFeeder\ConfigBundle\Form\Validator\Constraints\OnlyNumericValidator
        tags:
            - { name: validator.constraint_validator }
        arguments: ['@translator.default']
