services:
    user.form.registration:
        class: DogFeeder\UserBundle\Form\Type\RegistrationType
        tags:
            - { name: form.type, alias: user_registration }
        arguments: ['@translator.default']